spring:

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console

#  security:
#    user:
#      name: user
#      password: 1234

